### ISSUE TITLE
旅行证照片尺寸

### ISSUE THREAD

**Issue by jhliualan** [hjt486/passport-photo-maker#1]
2024年3月中国旅行证的照片尺寸为472x354。希望可以支持解锁长宽比。

**Comment by hjt486** [comment]
单纯解锁长宽比或导致比例失真，我增加了一个旅行证照片模板。我发现旅行证照片的问题是，在领事app上只有照片大小要求，其他一概没有说，所以我把尺寸改了，然后按照护照照片的要求等比例改小了参考线，其他没变，但是起码可以导出要求大小的照片了，已经更新发布了。
